### ISSUE TITLE
sign up bug

### ISSUE THREAD

**Issue by ggornes** [HairdressingProject/HairdressingApp#26]
Bug in api/users/sign_up when creating a user with an existing UserName and and existing UserEmail from another user. Example,

If in the database we have:
| id | user_name | user_email     | first_name | last_name | user_role |
|----|-----------|----------------|------------|-----------|-----------|
| 1  | test      | test@mail.com  | test       |           | user      |
| 2  | test2     | test2@mail.com | test       |           | user      |

Now, if we try sign up the following user:

{
	"UserName": "test",
	"UserEmail": "test@mail.com",
	"UserPassword": "123456",
	"FirstName": "test",
	"LastName": "",
	"UserRole": "user"
}

then we have this response from the server:

{
    "errors": {
        "users": [
            "User already registered"
        ]
    },
    "status": 409
}

But, if we try to sign up this user (notice that it has the user 1 UserName and user 2 UserEmail:

{
	"UserName": "test",
	"UserEmail": "test2@mail.com",
	"UserPassword": "123456",
	"FirstName": "test",
	"LastName": "",
	"UserRole": "user"
}

Then the server responds with a 500 Internal Server Error

**Comment by ggornes** [comment]
Server log:

System.InvalidOperationException: Enumerator failed to MoveNextAsync.
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at AdminApi.Controllers.UsersController.SignUp(Users users) in C:\Users\StudyPC\Diploma\Project\Team\HairdressingApp\Admin\Backend\AdminApi\Controllers\UsersController.cs:line 371
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
